[package]
name = "suzy_fontasset_builder"
version = "0.1.0"
authors = ["Violet <violet@geeklint.com>"]
edition = "2018"

[dependencies]
rayon = "1.3.0"
sha2 = "0.8.1"
hex = "0.4.2"
rusttype = "0.9.1"
