[package]
name = "suzy"
version = "0.1.0"
authors = ["Violet <violet@geeklint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drying_paint = "0.1.0"
