[package]
name = "suzy"
version = "0.1.0"
authors = ["Violet <violet@geeklint.com>"]
edition = "2018"

[features]
default = []
tui = []

[dependencies]
drying_paint = "0.1.0"

[build-dependencies]
bindgen = "0.52.0"
