[package]
name = "suzy"
version = "0.0.2-dev"
authors = ["Violet <violet@geeklint.com>"]
edition = "2018"
description = "GUI framework based on observer pattern"
homepage = "https://github.com/geeklint/suzy"
repository = "https://github.com/geeklint/suzy"
readme = "../README.md"
keywords = ["gui", "kivy", "widgets"]
license = "MPL-2.0"

[features]
default = ["sdl", "platform_osmesa"]
opengl = []
sdl = ["sdl2", "opengl"]
platform_osmesa = ["opengl"]

[dependencies]
drying_paint = "0.4.3"
gl = { version = "0.14.0", optional = true }

[dependencies.sdl2]
version = "0.33"
optional = true
default-features = false
features = ["image"]
