[package]
name = "suzy"
version = "0.0.2-dev"
authors = ["Violet <violet@geeklint.com>"]
edition = "2018"
description = "GUI framework based on observer pattern"
homepage = "https://github.com/geeklint/suzy"
repository = "https://github.com/geeklint/suzy"
readme = "README.md"
keywords = ["gui", "kivy", "widgets"]
license = "MPL-2.0"

[features]
default = ["sdl", "platform_osmesa"]
platform_opengl = []
platform_osmesa = ["platform_opengl"]
sdl = ["sdl2", "platform_opengl"]

[dependencies]
drying_paint = "0.4.5"

[dependencies.sdl2]
version = "0.33"
optional = true
default-features = false
features = ["image"]

[[example]]
name = "image"
required-features = ["platform_opengl"]
