name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt-get -y install libosmesa-dev libsdl2-dev
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Update Rust
      run: rustup update stable

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check macro formatting
      run: ./check_macro_fmt.bash

    - name: Clippy each feature set
      run: |
        cargo clippy --all-targets
        cargo clippy --all-targets --features "inline_tweak"
        cargo clippy --all-targets --features "platform_opengl"
        cargo clippy --all-targets --features "platform_sdl"
        cargo clippy --all-targets --features "platform_osmesa"
        cargo clippy --all-targets --features "platform_opengl default_font"
        cargo clippy --all-targets --features "quickstart"

    - name: Build
      run: cargo build --verbose --all-targets --all-features

    - name: Run tests
      run: cargo test --verbose --all-targets --all-features

    - name: Validate documentation
      run: cargo doc --no-deps --all-features
      env:
        RUSTDOCFLAGS: -Dwarnings