name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt-get -y install libosmesa-dev
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose --manifest-path suzy/Cargo.toml --no-default-features --features ci_build
    - name: Run tests
      run: cargo test --verbose --manifest-path suzy/Cargo.toml --no-default-features --features ci_build
    - name: Check formatting
      run: cargo fmt --all -- --check
